### ISSUE TITLE
A few questions...

### ISSUE THREAD

**Issue by coderberry** [otavioschwanck/mood-nvim#14]
Hey Octavio!

This has become my #1 editor now for Rails projects (and anything, really).

I was wondering a few things:

1. Can I sponsor you? Last time I spoke to you about this you said no, but I would love to support you somehow.
2. Would it be possible to keep a CHANGELOG for any major changes? I am not sure what changes once I sync my fork.
3. Do you have (or plan) on a way to add user configuration for plugins and configurations? It's pretty specific to your needs I think, and I could really use a clean way to:
	a. remove plugins (e.g. NerdCommenter vs Vim-Commentary)
    b. configure plugins (e.g. `let g:`)
  

I absolutely loved how you had all configurations in the Org files with your Doom Emacs configurations. I'm not sure if that's possible with this, but that would be incredible.

Please take all these questions/asks with a grain of salt. I am so grateful for you open-sourcing this and making my life TONS better!

Eric

**Comment by otavioschwanck** [comment]
Hi,

1. Really don't need it, my employees also uses this configuration so, its ok.

2. Today i finished to add the last feature i had planned (Switch between neovim / tmux panes with Alt + , and Alt + ;).  I won't make any more big changes because this configuration is already complete.  For now on, i will work just on my plugins (i have a feel planned, like ruby-refactor). I will just make fixes on this config based on new neovim versions and issues, and upgrade the plugins periodically (Lazy.nvim has a .lock file for plugin versions)

3. You can add plugins in your `SPC f p` -> plugins.

The syntax follows the https://github.com/folke/lazy.nvim .

You can just do something like:

```lua
return {
  { 'codeberry/my-awesome-plugin', config = function()
       require('codeberry').setup({ awesome = true })
   end },
   { 'awesome-dude/another-plugin' },
}
```

This will automatically install the plugins for you.  About removing the plugins, you can fork this config and remove by yourself on lua/plugins/**.lua


And thanks for your feedback, it make me so happy to know that guys like you are enjoying!

EDIT:

https://github.com/otavioschwanck/mood-nvim/issues/12#issuecomment-1414563425 (Important answer here hahah)

**Comment by coderberry** [comment]
As always, I really appreciate you man!

**Comment by thiagovsk** [comment]
wow
Thats amazing
@otavioschwanck I'd like to buy a bear for you, good job with this nvim mood!
